export const USER_ROLES = {
    ADMIN: 'ADMIN',
    VENDOR: 'VENDOR',
};

export const VENDOR_STATUS = {
    APPROVED: 'APPROVED',
    INACTIVE: 'INACTIVE',
    SUSPENDED: 'SUSPENDED',
    PENDING: 'PENDING',
};

export const PURCHASE_ORDER_STATUS = {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    SHIPPED: 'SHIPPED',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
};

export const UNIT_OF_MEASUREMENT = {
    KG: 'KG',
    GRAM: 'GRAM',
    TONNE: 'TONNE',
    LITER: 'LITER',
    PIECE: 'PIECE',
    BOX: 'BOX',
    METER: 'METER',
};

export const ORDER_ACTION_TYPE = {
    UPDATE: 'UPDATE',
    CANCEL: 'CANCEL',
    RETURN: 'RETURN',
};

export const ORDER_ACTION_STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
};

export const DOCUMENT_TYPE = {
    ISO_9001: 'ISO_9001',
    ISO_14001: 'ISO_14001',
    GST_CERTIFICATE: 'GST_CERTIFICATE',
    PAN_CARD: 'PAN_CARD',
    MSME_CERTIFICATE: 'MSME_CERTIFICATE',
    TRADE_LICENSE: 'TRADE_LICENSE',
    OTHER: 'OTHER',
};

export const DOCUMENT_TYPE_LABELS = {
    [DOCUMENT_TYPE.ISO_9001]: 'ISO 9001 Certificate',
    [DOCUMENT_TYPE.ISO_14001]: 'ISO 14001 Certificate',
    [DOCUMENT_TYPE.GST_CERTIFICATE]: 'GST Certificate',
    [DOCUMENT_TYPE.PAN_CARD]: 'PAN Card',
    [DOCUMENT_TYPE.MSME_CERTIFICATE]: 'MSME Certificate',
    [DOCUMENT_TYPE.TRADE_LICENSE]: 'Trade License',
    [DOCUMENT_TYPE.OTHER]: 'Other Document',
};